// sidebars.js

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide', // Generate sidebar from the 'user-guide' directory
    },
  ],
  developersGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developers-guide', // Generate sidebar from the 'developers-guide' directory
    },
  ],
  ...require("./sidebars-api.js")
};

module.exports = sidebars;